Ttree:
  Starter:
    nodeSorting:
      enable: false
      configuration:
        '/sites/officialwebsite/fr/participer':
          -
            type: Ttree.Plugin.MicroEvent:Event
            configuration:
              type:               simple
              property:           eventStartDate
              propertyTargetType: DateTime
